# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: blank
first_name: Xiaowen
middle_name:
last_name: Zhang
email: xiaowen5@andrew.cmu.edu
description: A simple, whitespace theme for academics.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

baseurl: ""
url: https://handshaker86.github.io

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/

imagemagick:
  enabled: false 

# jekyll_get_json:
#   - data: resume
#     json: assets/json/resume.json
# jsonresume:
#   - basics
#   - work

# scholar:
#   style: apa
#   source: /_bibliography/
#   bibliography: papers.bib

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2